apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: books-pg-cluster
spec:
  instances: 2
  bootstrap:
    initdb:
      database: books
      owner: myuser
      secret:
        name: cnpg-credentials
  storage:
    size: 1Gi
